first_app/urls.py
from django.urls import path

from . import views

app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('formpage/', views.form_view, name='formpage'),
    path('signup/', views.sign_up, name='signup'),
    path('first_app/', views.index, name='index'),
    path('registration/', views.register, name='register'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.PROTECT)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class Userz(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254, unique=True)


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import Userz, UserProfileInfo
from django.contrib.auth.models import User


def check_for_name(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to start with Z")


class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_name])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again:')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput)
    botcatcher2 = forms.CharField(required=False,
                                  widget=forms.HiddenInput,
                                  validators=[validators.MaxLengthValidator(0)]
                                  )

    def clean_botcatcher(self):
        data = self.cleaned_data['botcatcher']
        if len(data) > 0:
            raise forms.ValidationError("GOTCHA BOT!")
        return data

    # def clean(self): validate of the fileds at once
    #    all_clean_data = super().clean()


class NewUserForm(forms.ModelForm):
    class Meta():
        model = Userz
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_app/views.py
from django.shortcuts import render
from first_app.models import AccessRecord
from . import forms


def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpage_list}
    return render(request, 'first_app/index.html', context=date_dict)


def form_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print("VALIDATION SUCCESS")
            print("Name: " + form.cleaned_data['name'])
            print("Email: " + form.cleaned_data['email'])
            print("Text: " + form.cleaned_data['text'])

    return render(request, 'first_app/form_page.html', context={'form': form})


def sign_up(request):
    form = forms.NewUserForm()

    if request.method == 'POST':
        form = forms.NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    return render(request, 'first_app/signup.html', context={'form': form})


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'first_app/registration.html',
                           {'user_form': user_form,
                            'profile_form': profile_form,
                            'registered': registered
                            })

templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="navbar-brand"><a href="#">BRAND</a></li>
        <li><a class="navbar-link" href="{% url 'first_app:signup' %}">SIGNUP</a></li>
        <li><a class="navbar-link" href="{% url 'first_app:index' %}">INDEX</a></li>
        <li><a class="navbar-link" href="{% url 'first_app:formpage' %}">FORMPAGE</a></li>
        <li><a class="navbar-link" href="{% url 'first_app:register' %}">REGISTER</a></li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>

templates/first_app/form_page.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<body>
  <h1>Fill out the form</h1>
  <div class="container">
    <form method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
  </form>
  </div>
{% endblock %}

templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
  <h1>Hi Welcome</h1>
  <h2>Here are you access records</h2>
  <a href="{% url 'first_app:signup' %}">Sign Up</a>
  <div class="djangotwo">
    {% if access_records %}
    <table>
      <thead>
        <th>Site Name</th>
        <th> Date Accessed</th>
      </thead>
      {% for acc in access_records %}
      <tr>
        <td>{{ acc.name }}</td>
        <td>{{ acc.date }}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <p>No Access Records</p>
    {% endif%}

  </div>
{% endblock %}

templates/first_app/login.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% usrl 'first_app:login'%}" method='POST'>
      {% csrf_token %}
      <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">
    </form>
  </div>
{% endblock %}

templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registring</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Fill put the form</h3>

    <form method="POST" enctype="multipart/form-data">
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Register">
    </form>
    {% endif %}

  </div>
  <div class="container">
    <a href="{% url 'first_app:index' %}" >Home Page</a>
  </div>
{% endblock %}

templates/first_app/signup.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
  <div class="container"
    <h1>Sign Up!</h1>
    <form method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  </div>
  <div class="container">
    <a href="{% url 'first_app:index' %}" >Home Page</a>
  </div>
{% endblock %}